cfg: root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/cfg.yaml
train:
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_172
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_103
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_496
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_459
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_113
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_419
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_271
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_335
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_484
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_129
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_314
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_489
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_87
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_467
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_72
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_339
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_291
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_442
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_425
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_307
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_194
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_301
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_199
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_319
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_192
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_358
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_465
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_69
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_33
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_50
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_54
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_303
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_400
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_7
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_193
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_16
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_160
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_237
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_123
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_189
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_487
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_93
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_446
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_265
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_346
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_474
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_283
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_236
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_75
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_197
val:
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_85
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_428
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_257
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_305
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_249
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_130
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_384
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_119
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_97
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_63
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_388
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_155
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_0
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_248
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_455
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_164
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_153
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_430
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_206
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_255
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_460
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_65
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_332
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_203
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_337
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_183
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_169
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_10
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_321
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_373
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_494
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_325
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_5
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_79
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_22
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_239
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_403
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_451
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_126
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_324
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_162
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_218
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_173
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_227
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_441
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_261
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_215
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_318
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_498
