cfg: root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/cfg.yaml
train:
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_462
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_424
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_207
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_27
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_259
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_209
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_469
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_471
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_49
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_431
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_184
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_315
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_190
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_219
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_176
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_353
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_45
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_38
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_135
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_242
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_483
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_394
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_458
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_196
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_217
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_15
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_287
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_204
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_491
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_267
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_191
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_41
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_24
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_246
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_234
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_163
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_231
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_395
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_347
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_208
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_281
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_44
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_266
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_466
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_42
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_23
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_195
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_409
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_482
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_53
val:
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_85
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_428
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_257
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_305
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_249
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_130
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_384
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_119
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_97
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_63
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_388
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_155
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_0
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_248
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_455
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_164
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_153
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_430
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_206
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_255
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_460
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_65
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_332
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_203
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_337
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_183
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_169
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_10
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_321
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_373
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_494
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_325
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_5
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_79
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_22
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_239
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_403
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_451
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_126
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_324
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_162
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_218
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_173
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_227
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_441
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_261
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_215
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_318
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_498
