cfg: root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/cfg.yaml
train:
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_484
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_475
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_404
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_132
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_354
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_245
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_161
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_197
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_78
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_491
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_251
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_93
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_243
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_493
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_377
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_237
val:
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_85
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_428
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_257
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_305
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_249
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_130
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_384
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_119
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_97
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_63
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_388
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_155
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_0
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_248
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_455
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_164
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_153
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_430
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_206
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_255
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_460
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_65
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_332
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_203
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_337
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_183
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_169
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_10
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_321
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_373
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_494
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_325
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_5
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_79
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_22
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_239
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_403
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_451
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_126
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_324
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_162
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_218
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_173
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_227
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_441
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_261
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_215
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_318
- root://cmsdcache-kit-disk.gridka.de//store/user/tvoigtlaender/TAUML/january_2025_V5/RootToTF/ShuffleMergeSpectral_498
