# basic imports
defaults:
  - discriminator: DeepTau_run3
  - selection
  - _self_

# mflow run info
path_to_mlflow: /work/tvoigtlaender/checkpointing/TauMLTools/data/Training/full_run_V1/files/mlruns
experiment_id: 12
run_id: a49f211122864ff5bb8b655ca60f0332
# path_to_mlflow: /work/tvoigtlaender/checkpointing/TauMLTools/data/Training/2024_aug_long_norecompute_V1/files/mlruns/
# experiment_id: 362433441758125928
# run_id: 6c30af7daec845a188d631979316a20f

# phase space region
# vs_type: mu # jet/e/mu
vs_type: jet # jet/e/mu
dataset_alias: tau_ggH_jet_TT # alias to reference a mixture of input_samples below, e.g. tau_DY_jet_TT
pt_bins: [[20, 100], [100, 1000]]
eta_bins: [[0, 2.3]]
dm_bins: [[0, 1, 2, 10, 11]]

# selection
input_branches: [ 'tau_pt', 'tau_eta', 'tau_decayMode' , 'tau_dz', 'tau_phi'] # add here WP branches if necessary 
cuts: "(${apply_dm_cuts}) and (abs(tau_dz) < 0.2)" 
WPs_to_require: null # null to not apply WP as selection
# WPs_to_require: ### example for vs. jet
#   e: VVVLoose
#   mu: VLoose

# inputs/paths
input_samples: # "sample_alias": [list of strings with tau types to be selected]
  GluGluHToTauTau_M125_v4: ['tau']
  # DYJetsToLL_M-50-amcatnloFXFX_ext2_v4: ["${vs_type}"]
  TTToSemiLeptonic_v4: ["${vs_type}"]
path_to_input: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*/{tau_type}/predictions.h5'
path_to_pred: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*/{tau_type}/predictions.h5'
path_to_target: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*/{tau_type}/predictions.h5'
path_to_weights_taus: null
path_to_weights_vs_type: null

# misc.
roc_prune_decimal: # precision on TPR rounding 
  e: 3
  mu: 4
  jet: 3
